### ISSUE TITLE
Ability to deploy new charts with predefined values.yaml

### ISSUE THREAD

**Issue by slamer59** [komodorio/helm-dashboard#134]
Hello,
I have some applications that don't require to run all day long. A UI that will help to store and deploy,uninstall some charts. would be really nice feature. 

A kind of launcher in fact. 

Happy to discuss further if needed.

**Comment by undera** [comment]
This sounds interesting, but I did not understand it fully. Do you mean that you want to remember values.yaml for the chart when you uninstall it, and then offer it once you install it again?

**Comment by slamer59** [comment]
Yes. Exactly. See it as an application launcher. In [Lens](https://k8slens.dev/) for exemple you : 
- register your chart (git / helm repo)
- load the definition and install/update the chart

Benefits: 
- it is installed in k8s so anyone with access can do this fast
- store the values
- Resource usage.
- one interface endpoint for many admin application

**Comment by appdirect-kasidit** [comment]
I'm not sure if it's the same with this use case, but it'd be nice if we can have predefined non-default values file that we can select via UI and will automatically load into the user defined panel.

My example use case would be if we have a chart that has multiple database engine that we can choose

Default `values.yaml`
```yaml
mysql:
    enabled: false
    # configurations

postgres:
    enabled: false
    # configurations
```
Then in my predefined `values.mysql.yaml`
```yaml
mysql:
    enabled: true
    # configurations
```
and my predefined `values.postgres.yaml`
```yaml
postgres:
    enabled: true
    # configurations
```
