### ISSUE TITLE
Helm chart installation doesn't show any charts

### ISSUE THREAD

**Issue by ruzickap** [komodorio/helm-dashboard#217]
### Description

I installed the [helm-dashboard](https://github.com/komodorio/helm-dashboard) using the helm chart described here: https://github.com/komodorio/helm-charts/tree/master/charts/helm-dashboard

Unfortunately I do not see any Installed charts:

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/1434387/219291982-1375e4ae-3b69-4dc3-84eb-512927cb563a.png">

There are many of them on the cluster which is running [helm-dashboard](https://github.com/komodorio/helm-dashboard):

```bash
❯ helm ls -A                                                                                                                                                       ⎈ mgmt01
NAME                    	NAMESPACE                	REVISION	UPDATED                                	STATUS  	CHART                                                                                   	APP VERSION
aws-ebs-csi-driver      	aws-ebs-csi-driver       	1       	2023-02-16 05:03:57.450296564 +0000 UTC	deployed	aws-ebs-csi-driver-2.17.0                                                               	1.16.0
cert-manager            	cert-manager             	1       	2023-02-16 05:06:25.522097992 +0000 UTC	deployed	cert-manager-v1.11.0                                                                    	v1.11.0
cnpg                    	cnpg-system              	1       	2023-02-16 05:06:55.508180141 +0000 UTC	deployed	cloudnative-pg-0.17.0                                                                   	1.19.0
crossplane              	crossplane-system        	1       	2023-02-16 05:02:28.862560764 +0000 UTC	deployed	crossplane-1.11.0                                                                       	1.11.0
dex                     	dex                      	1       	2023-02-16 05:10:14.121739678 +0000 UTC	deployed	dex-0.13.0                                                                              	2.35.3
external-dns            	external-dns             	1       	2023-02-16 05:07:22.217294821 +0000 UTC	deployed	external-dns-6.13.3
```

There are no other details in the logs:

```bash
❯ kubectl logs -n helm-dashboard helm-dashboard-f94df8567-s6wqq
time="2023-02-16T05:03:23Z" level=info msg="Helm Dashboard by Komodor, version 1.0.0 (none @ unknown)"
time="2023-02-16T05:03:23Z" level=info msg="Got no kubectl config contexts, will attempt to detect if we're inside cluster..."
time="2023-02-16T05:03:23Z" level=warning msg="Newer Helm Dashboard version is available: v1.1.0"
time="2023-02-16T05:03:23Z" level=warning msg="Upgrade instructions: https://github.com/komodorio/helm-dashboard#installing"
time="2023-02-16T05:03:25Z" level=info msg="Discovered Checkov version: 2.1.244"
time="2023-02-16T05:03:25Z" level=info msg="Discovered Trivy: Version: 0.18.3"
time="2023-02-16T05:03:25Z" level=info msg="User analytics is collected to improve the quality, disable it with --no-analytics"
time="2023-02-16T05:03:25Z" level=info msg="Access web UI at: http://0.0.0.0:8080"
[GIN] 2023/02/16 - 05:03:30 | 200 |     136.831µs |      10.0.1.248 | GET      "/status"
...
``` 

I used the following Helm values when installed the `helm-dashboard`:

```yaml
dashboard:
  # allowWriteActions: false
  persistence:
    enabled: false
ingress:
  enabled: true
  className: nginx
  annotations:
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/icon: "https://raw.githubusercontent.com/komodorio/helm-dashboard/9bb597f366426daa2ada06fb87eee2094e862aa3/pkg/dashboard/static/logo.svg"
    forecastle.stakater.com/appName: Helm Dashboard
    nginx.ingress.kubernetes.io/auth-url: https://oauth2-proxy.${CLUSTER_FQDN}/oauth2/auth
    nginx.ingress.kubernetes.io/auth-signin: https://oauth2-proxy.${CLUSTER_FQDN}/oauth2/start?rd=$scheme://$host$request_uri
  hosts:
    - host: helm-dashboard.${CLUSTER_FQDN}
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - helm-dashboard.${CLUSTER_FQDN}
```

> When I run `helm dashboard` command locally - I also can not see any helm charts installed.
(but I can see the helm repositories).

Any ideas why it is not working?

Thank you

**Comment by undera** [comment]
If you don't see any charts even when running locally - then we need to understand is it a frontend or backend problem. Unfortunately, I don't see any easy answers and I'll need some of your help to debug it.

Do you see any errors in JS console of your browser? Also, are there any namespace access limitations for your cluster access?

**Comment by undera** [comment]
Another option to try is to specify a namespace with `--namespace` parameter, and see if it would work with only accessing specific namespace. If it works, you can specify the list of accessible namespaces, separated by comma.

**Comment by ruzickap** [comment]
I tried to run the helm-dashboard locally and here are few details.

```bash
❯ export KUBECONFIG=/tmp/kubeconfig-eks-01.conf
❯ cat "${KUBECONFIG}"
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1xxxxxxx0tLS0tCg==
    server: https://CxxxxxxxF.gr7.eu-central-1.eks.amazonaws.com
  name: ruzickap-eks-01.eu-central-1.eksctl.io
contexts:
- context:
    cluster: ruzickap-eks-01.eu-central-1.eksctl.io
    user: aws-cli@ruzickap-eks-01.eu-central-1.eksctl.io
  name: aws-cli@ruzickap-eks-01.eu-central-1.eksctl.io
current-context: aws-cli@ruzickap-eks-01.eu-central-1.eksctl.io
kind: Config
preferences: {}
users:
- name: aws-cli@ruzickap-eks-01.eu-central-1.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - token
      - -i
      - ruzickap-eks-01
      command: aws-iam-authenticator
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      - name: AWS_DEFAULT_REGION
        value: eu-central-1
      provideClusterInfo: false
```

It is a standard Amazon EKS cluster created by [eksctl](https://eksctl.io/).

I tried the suggested `helm dashboard --namespace cert-manager` parameter and it is still the same - no helm charts.

---

You can easily reproduce the issue by running the following commands (in case you have AWS account):

```bash
export KUBECONFIG=/tmp/kubeconfig.conf

eksctl create cluster \
  --name=${USER}-k8s \
  --region=eu-central-1 \
  --zones=eu-central-1a,eu-central-1b \
  --kubeconfig="${KUBECONFIG}"

helm upgrade --install podinfo oci://ghcr.io/stefanprodan/charts/podinfo

helm dashboard
helm dashboard --namespace default
```

Thanks...

**Comment by zhekazuev** [comment]
Hello, Petr.

I have been experiencing the same problem.
I think `helm-dashboard` has performance issues and can't see all the charts installed in all nimespaces if you have it too many.
And for example if you have more than 20 installed charts in a cluster, this can cause errors and long downloads.

You can check if `helm-dashboard` works at all by using the following value in your file:
```yaml
# your values are unchanged here
...
dashboard:
  namespace: "crossplane"
...
# your values are unchanged here
```

Where `crosplane` is the namespace (taken from your example) in which you want the `helm-dashboard` to look for installed charts.
I recommend checking with just one namespace to begin with.

You can use not just one namespace, but several(without spaces), e.g. `namespace: "crosplane,cert-manager,dex"`.

But as I said, `helm-dashboard` has a performance problem, and if you use many namespaces with helm-dashboard or all (`namespace: ""`), this will be a problem.

You can also add more pods (you will have to do this manually because there is a bug in the chart itself) or resources to speed up the loading of charts.
I set 1cpu request and 2 cpu limit and 2-3 pods.

You can check how `helm-dashboard` uses resources using this command: `watch kubectl -n helm-dashboard top pods` and try reloading the page while the command is active.
I think you can observe more than 1 CPU load if you have a lot of charts installed (like 20+, in my case it was more than 100).

Will you be able to do a test and let us know?
