### ISSUE TITLE
Storage class should be set or omitted on pvc

### ISSUE THREAD

**Issue by jscharber** [komodorio/helm-dashboard#226]
### Description

Microk8s fails to create the pv for the associated pvc because a ```storageClassName: ""``` is specified but left blank.   As a result, the default storage class is not assigned.

The logic around storage is based on naming conventions rather than explicitly declaring what is wanted.  Maybe something like this:

```yaml
persistence:
  - enabled: true
  - isDynamicPV: true
  - setStorageClass: false
  - storageClassName: ""
```
 
the details

Looking at the values file
```
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    storageClass: ""
```
Then the source code https://github.com/komodorio/helm-dashboard/blob/7a253350287c4216b4deb1c7cc2af441006f84d0/charts/helm-dashboard/templates/pvc.yaml

```
Source: helm-dashboard/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helm-dashboard
  namespace: "harbor"
  labels:
    helm.sh/chart: helm-dashboard-0.1.5
    app.kubernetes.io/name: helm-dashboard
    app.kubernetes.io/instance: helm-dashboard
    app.kubernetes.io/version: "1.1.1"
    app.kubernetes.io/managed-by: Helm
spec:
  storageClassName: ""
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "100M"
```
