### ISSUE TITLE
Add Support for Preconfigured Helm Repositories via Values File

### ISSUE THREAD

**Issue by josephaw1022** [komodorio/helm-dashboard#549]
### Description

Currently, the Helm Dashboard UI requires manual input to add Helm chart repositories whenever a new cluster is spun up. This can become repetitive and inefficient for users who manage multiple clusters or frequently create new clusters. It would be beneficial if the repositories could be pre-configured via the values.yaml file during the initial setup, allowing the Helm Dashboard to automatically populate the UI with the predefined repositories. This would save time and reduce manual intervention.

### Screenshots

![image](https://github.com/user-attachments/assets/cc2f82d0-070f-4563-a517-ef343a3dc576)

### Additional information

**Proposed Solution:**

Introduce the ability to define Helm repositories in the values.yaml file. These values would then be passed into the deployment as environment variables or mounted as a configuration file.
Application Reads Configuration:

The Helm Dashboard would read the Helm repository configurations either from environment variables or a file at runtime. The configuration could be handled using a ConfigMap in Kubernetes.

```yaml

repositories:
    - name: "Komodor"
      url: "https://helm-charts.komodor.io"
    - name: "argo"
      url: "https://argoproj.github.io/helm-chart"

```

probably would need to think about the username and password fields as well.
